const initialValues = {
  currency_type: "US Dollar (USD)",
  port1: "Bangkok (BK)",
  port1_fees: "10.5",
  port1_port_call: "3.2",
  port1_crane_usage: "2.8",
  port2: "Batam (BAT)",
  port2_fees: "0",
  port2_port_call: "0",
  port2_crane_usage: "0",
  port3: "NIL",
  port3_fees: "0",
  port3_port_call: "0",
  port3_crane_usage: "0",
  port4: "NIL",
  port4_fees: "0",
  port4_port_call: "0",
  port4_crane_usage: "0",
  port5: "NIL",
  port5_fees: "0",
  port5_port_call: "0",
  port5_crane_usage: "0",
  port6: "NIL",
  port6_fees: "0",
  port6_port_call: "0",
  port6_crane_usage: "0",
  cargo1: "Palm Kernel Shell (PKS)",
  cargo1_quantity: "3000",
  cargo1_rate: "22",
  cargo2: "NIL",
  cargo2_quantity: "0",
  cargo2_rate: "0",
  cargo3: "NIL",
  cargo3_quantity: "0",
  cargo3_rate: "0",
  cargo4: "NIL",
  cargo4_quantity: "0",
  cargo4_rate: "0",
  cargo5: "NIL",
  cargo5_quantity: "0",
  cargo5_rate: "0",
  cargo6: "NIL",
  cargo6_quantity: "0",
  cargo6_rate: "0",
  bunker_rate: "22",
  diesel_rate: "28",
  lube_rate: "0",
  brokerage_fees: "3.75",
  surveying_fees: "1000",
  miscCosts: "2000",
};
{
    "queryStringParameters": {
      "currency_type": "US Dollar (USD)",
      "port1": "Bangkok (BK)",
      "port1_fees": "10.5",
      "port1_port_call": "3.2",
      "port1_crane_usage": "2.8",
      "port2": "Batam (BAT)",
      "port2_fees": "0",
      "port2_port_call": "0",
      "port2_crane_usage": "0",
      "port3": "NIL",
      "port3_fees": "0",
      "port3_port_call": "0",
      "port3_crane_usage": "0",
      "port4": "NIL",
      "port4_fees": "0",
      "port4_port_call": "0",
      "port4_crane_usage": "0",
      "port5": "NIL",
      "port5_fees": "0",
      "port5_port_call": "0",
      "port5_crane_usage": "0",
      "port6": "NIL",
      "port6_fees": "0",
      "port6_port_call": "0",
      "port6_crane_usage": "0",
      "cargo1": "Palm Kernel Shell (PKS)",
      "cargo1_quantity": "3000",
      "cargo1_rate": "22",
      "cargo2": "NIL",
      "cargo2_quantity": "0",
      "cargo2_rate": "0",
      "cargo3": "NIL",
      "cargo3_quantity": "0",
      "cargo3_rate": "0",
      "cargo4": "NIL",
      "cargo4_quantity": "0",
      "cargo4_rate": "0",
      "cargo5": "NIL",
      "cargo5_quantity": "0",
      "cargo5_rate": "0",
      "cargo6": "NIL",
      "cargo6_quantity": "0",
      "cargo6_rate": "0",
      "bunker_rate": "22",
      "diesel_rate": "28",
      "lube_rate": "0",
      "brokerage_fees": "3.75",
      "surveying_fees": "1000",
      "miscCosts": "2000"
    }
  }
  